### ISSUE TITLE
提示“无法加载无效的文件”

### ISSUE THREAD

**Issue by TmallBoss** [FoundTheWOUT/utools-excalidraw#1]
画好的图导出文件后无法再导入。一直提示无法打开无效的文件。
[无标题-2023-02-15-1016.excalidraw.zip](https://github.com/FoundTheWOUT/utools-excalidraw/files/10868189/-2023-02-15-1016.excalidraw.zip)
[无标题-2023-02-15-1016.excalidraw.zip](https://github.com/FoundTheWOUT/utools-excalidraw/files/10868195/-2023-02-15-1016.excalidraw.zip)

**Comment by FoundTheWOUT** [comment]
我看下，你这个是空文件
![image](https://user-images.githubusercontent.com/47922588/223036180-84832778-ed58-4157-9a6a-56da472cfbd7.png)
文件是从插件导出的吗，如果是从插件导出的话，可以说下导出操作吗

**Comment by TmallBoss** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    是从插件导出的，我刚录屏发过去了，但是好像不支持发送录屏。具体操作为：1. 基于插件点击左侧菜单栏；2. 点击「保存到···」按钮；
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Me
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2023年03月6日 ***@***.***> 写道： 




我看下，你这个是空文件



文件是从插件导出的吗，如果是从插件导出的话，可以说下导出操作吗



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by FoundTheWOUT** [comment]
录屏的话可能需要你在网页版上把视频插入进来。你的操作系统是什么

**Comment by TmallBoss** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    MacOS  BigSur 11.6.5 方便加QQ或者微信吗
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                Me
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2023年03月6日 ***@***.***> 写道： 




录屏的话可能需要你在网页版上把视频插入进来。你的操作系统是什么



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by FoundTheWOUT** [comment]
你把QQ号发我邮件吧，我邮件地址可以在我主页看到

**Comment by TmallBoss** [comment]
发你了

**Comment by TmallBoss** [comment]
[尴尬，又被退信了。
