### ISSUE TITLE
【bug】无法打开具体画布

### ISSUE THREAD

**Issue by HALOXIAO** [FoundTheWOUT/utools-excalidraw#14]
mac m1 pro，Ventura 13.5 ，utools：4.0.0，某一天突然无法进入画布

<img width="912" alt="image" src="https://github.com/FoundTheWOUT/utools-excalidraw/assets/45111269/5570ef4d-79ab-4cc7-89ed-2933e6fde65b">

**Comment by FoundTheWOUT** [comment]
看起来像是侧栏沾满了整个app ，不过为啥操作画布的按钮也没了……

可以尝试一下混动到最顶部，看下能不能打开设置面板，然后关闭侧栏

**Comment by HALOXIAO** [comment]
> 看起来像是侧栏沾满了整个app ，不过为啥操作画布的按钮也没了……
> 
> 可以尝试一下混动到最顶部，看下能不能打开设置面板，然后关闭侧栏
我尝试过滑动到最顶部和最低部，各种能尝试的操作包括但不限于：新增画布尝试进入、通过快捷键（Enter）或者双击等方式尝试进入、卸载 utools 并重新安装最新版本；我可以提供哪些信息以便更好的定位到异常呢？

**Comment by FoundTheWOUT** [comment]
emm，你滚动到顶部截个图我看看，现在是不是无法打开设置面板。
可以把插件版本也提供一下吗~

**Comment by HALOXIAO** [comment]
> 
最顶部：
<img width="846" alt="image" src="https://github.com/FoundTheWOUT/utools-excalidraw/assets/45111269/2e74e9c8-b46b-41bf-abc9-4c6323c4bc30">

版本：0.13.1

**Comment by HALOXIAO** [comment]
> 

对的，无法打开设置面板

**Comment by FoundTheWOUT** [comment]
这也太神奇了。。难道和系统有关吗

**Comment by HALOXIAO** [comment]
> 这也太神奇了。。难道和系统有关吗

应该不是，我有挺长一段时间没有更新系统了

**Comment by HALOXIAO** [comment]
> 

在 windows 环境下也存在这个问题

**Comment by HALOXIAO** [comment]
我认为可能是settings 中数据的问题，这是我的数据：

{
    "value": {
        "asideWidth": -1,
        "asideClosed": true,
        "lastActiveDraw": "Va14x9",
        "closePreview": false,
        "scenesId": [
            "kFAdIx",
            "95HEXN",
            "htYEmt"
        ],
        "asideCloseAutomatically": false,
        "deleteSceneDirectly": false
    },
    "_id": "settings",
    "_rev": "1854-9a9176e4142099d9e530318ad81ba54f"
}

**Comment by FoundTheWOUT** [comment]
哎，你的 `asideClosed` 是 true 怎么还会显示侧栏呢

**Comment by FoundTheWOUT** [comment]
@HALOXIAO  方便留个邮箱吗

**Comment by FoundTheWOUT** [comment]
@HALOXIAO hallo，新版有解决你的问题吗

**Comment by HALOXIAO** [comment]
> 

QAQ并没有

**Comment by HALOXIAO** [comment]
> 昨天发了一版，可以看看🙏

非常感谢～ 已经能够正常使用了
