### ISSUE TITLE
你好，可以支持中文字体么

### ISSUE THREAD

**Issue by Skypow2012** [FoundTheWOUT/utools-excalidraw#16]
比如用户自己添加中文字体，然后选中
https://sspai.com/post/71244

**Comment by FoundTheWOUT** [comment]
Obsidian 的手写是自己 clone 一份 Excalidraw 来维护的。我现在没这个打算~
还是等官方支持吧，虽然不知道最终有没有结果
https://github.com/excalidraw/excalidraw/pull/5604

**Comment by xibaoning** [comment]
中文没有手写效果呢，

**Comment by FoundTheWOUT** [comment]
ref https://github.com/excalidraw/excalidraw/issues/8408
